---
title: "Assignment6"
autho: "Wongel Molla"
output: html_document
---
library(tidyverse)
data <- read.csv("C:\\Users\\wonge\\Desktop\\occupation1870.csv")
head(data)
summarize(data)
summary(data)
colnames(data)

data_long <- data%>%
rename(State = Area.name)%>%
pivot_longer( 
cols = c(Agriculture.Male,Agriculture.Female,Manufacturing.Male,Manufacturing.Female,Trade.Male,Trade.Female,Service.Male,Service.Female,School.Male,School.Female),
names_to = "occupation_gender",
values_to = "values"
)%>%
separate(occupation_gender, c("Occupation","Gender"), sep ="\\.")%>%
pivot_wider(
names_from = "Gender",
values_from = "values")

ggplot(data_long, aes(x = Female, y = Male, color = State )) +
  geom_point(alpha= 0.9, size= 3) +
  facet_wrap(~Occupation) +
  theme_minimal() +
  labs(title = "Occupation According to Sex", 
       x= "Number of Females",
       y="Number of Males")+
  theme(
  legend.position= "bottom",
  legend.key.size= unit(.1, "cm"))
  
  summary(data_long)
  
  #In every occupation except School, the number of males significantly outnumber the number of females. The minimum for the number of males employed in any occupation is 79, while it is 0 for females.Trade has the lowest number of female employment while school has the highest.
  
